server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE:wit}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:wit}
    password: ${MYSQL_PASSWORD:wit}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
  main:
    banner-mode: "off"
